### PR TITLE
Update composer packages

### PR DESCRIPTION
**Pull request by kenjis**
We can't run `composer install` with Composer v2.
This PR fixes it.

```sh-session
$ composer install
Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.
Your lock file does not contain a compatible set of packages. Please run composer update.

  Problem 1
    - dealerdirect/phpcodesniffer-composer-installer is locked to version v0.5.0 and an update of this package was not requested.
    - dealerdirect/phpcodesniffer-composer-installer v0.5.0 requires composer-plugin-api ^1.0 -> found composer-plugin-api[2.0.0] but it does not match the constraint.

You are using Composer 2, which some of your plugins seem to be incompatible with. Make sure you update your plugins or report a plugin-issue to ask them to support Composer 2.
```

Includes:
- update `phpcodesniffer-composer-installer` for composer v2
- update PHPUnit to `^7.0`
- update Travis PHP versions
- fix coding style with `vendor/squizlabs/php_codesniffer/phpcs.xml.dist`
- remove `composer.lock`
- add `composer test` command

### CODE REVIEW

**Comment by kenjis** [comment]
```sh-session
$ vendor/bin/phpunit --filter CodeIgniter4
PHPUnit 6.5.14 by Sebastian Bergmann and contributors.

.........                                                           9 / 9 (100%)

9 sniff test files generated 25 unique error codes; 22 were fixable (88%)

Time: 3.51 seconds, Memory: 30.00MB

OK (9 tests, 0 assertions)

Generating code coverage report in Clover XML format ... done

Generating code coverage report in HTML format ... done
```

**Comment by kenjis** [comment]
It seems we must update PHPUnit to version 9.3.

https://travis-ci.org/github/codeigniter4/coding-standard/jobs/761060422
```sh-session
Your requirements could not be resolved to an installable set of packages.

  Problem 1

    - phpunit/phpunit[6.5.0, ..., 6.5.14] require php ^7.0 -> your php version (8.0.2) does not satisfy that requirement.

    - Root composer.json requires phpunit/phpunit ^6.5 -> satisfiable by phpunit/phpunit[6.5.0, ..., 6.5.14].
```

**Comment by kenjis** [comment]
PHP_CodeSniffer does not support PHPUnit 8 or later:
https://github.com/squizlabs/PHP_CodeSniffer/blob/1106d65547e581a5184a9293486d9e6d81595462/composer.json#L34

**Comment by kenjis** [comment]
@louisl Could you review this?

**Comment by louisl** [comment]
@kenjis Thanks for the PR, I'll check it out ASAP.

**Comment by kenjis** [comment]
@louisl Thanks!

**Comment by kenjis** [comment]
@louisl When I `composer update` in CI4, `codeigniter4-standard` does not update.
See #37

**Pull request merged**
