### PR TITLE
Allow single line doc comments

### LINKED ISSUE #33: phpcbf breaks /** @var ... */
```diff
--- a/system/BaseModel.php
+++ b/system/BaseModel.php
@@ -299,7 +299,9 @@ abstract class BaseModel
        $this->tempUseSoftDeletes = $this->useSoftDeletes;
        $this->tempAllowCallbacks = $this->allowCallbacks;
 
-       /** @var Validation $validation */
+       /**
+ * @var Validation $validation
+*/
        $validation = $validation ?? Services::validation(null, false);
 
        $this->validation = $validation;
```

### PR DESCRIPTION
**Pull request by kenjis**
Fixes #33

### CODE REVIEW

**Review by MGatner — APPROVED** [review]
Are there ways to test these things? Or are these pretty well tested at the tool source?

**Comment by louisl** [comment]
@MGatner
@kenjis 

Sorry guys real busy with work at the moment, I'll be able to take a look over the weekend.

It needs a unit test to confirm it's processing as expected. 

Also need to check whether it's actually valid for phpDocumentor because it's not just about dev comments and IDE autocomplete, you should be able to generate logical valid docs.

@kenjis Can you please change the PR's to the develop branch. I've been using gitflow and keep master to release only, we could change this to github workflow and just use master tags for releases. I'm in two minds whether to start using that workflow instead it would be more beneficial for users to be able to use 'dev-master' I guess?

**Comment by kenjis** [comment]
I've changed the base.

I don't know how to write unit tests for this, and how to check valid for phpDocumentor.

**Comment by kenjis** [comment]
@louisl The current default branch of this repository is `master`.
If you want PRs to `develop`, it is better you change the branch.

**Comment by louisl** [comment]
> I've changed the base.
> 
> I don't know how to write unit tests for this, and how to check valid for phpDocumentor.

Thanks, I'll write the tests this weekend. phpDocumentor's a case of reading the docs and running phpdoc and checking it makes sense, I should probably find out if there's a way I can automate that.

**Pull request merged**
