### PR TITLE
Workaround for wrong indentation in array

### PR DESCRIPTION
**Pull request by kenjis**
Workaround for #41

### CODE REVIEW

**Comment by MGatner** [comment]
Please wildcard `en` as well since this will apply to all languages.

**Comment by kenjis** [comment]
I've changed the exclude pattern.

**Review by MGatner — APPROVED** [review]

**Review by paulbalandan — APPROVED** [review]

**Comment by MGatner** [comment]
I'm not sure who is in charge here. @louisl ? I can proceed with the merge but don't want to step on any toes. We would definitely like to have this.

**Comment by louisl** [comment]
Apologies, I've had a busy few weeks and haven't managed to get around to it, I'll get this done today

**Comment by MGatner** [comment]
@louisl Any update on this? I think this change is pretty non-intrusive so I'm inclined just to merge it but don't want to intrude on your territory.

**Comment by louisl** [comment]
@MGatner Merged this and the other PR’s to develop downloaded it to prepare for a release and my computer died, spent all day trying to fix it but the HD is knackered. It’s getting on a bit and I was thinking about an upgrade. So I’ve ordered a new Mac coming tomorrow, will restore etc then I’ll do the release, so tomorrow night UK time (29th) realistically.

**Comment by MGatner** [comment]
@louisl so sorry to hear about your compy! I hope you enjoy the new one. Let me know if you want any help in the meantime, I'm glad to do a release.

**Pull request merged**
