### PR TITLE
Updates to the Ruleset

### PR DESCRIPTION
**Pull request by najdanovicivan**
Some updates done to the rule set
- Line length increased to 250 characters
- Function @param comment - Do not enforce capital letter
- Function @throws comment - Do not enforce dot at the end
- Function @throws comment - Do not enforce capital letter
- Function @throws comment - Makes it optional

File and Class comment rule changes. This is because mostly all of the existing files are missing those. We can either disable those for now and I can go latter on and update every file
- @package I don't know if we need it it should be first namespace level under CodeIgniter
- @licence - We can link the license in every file
- @author - Can be added from the git commit logs

With all of these I increased the version to 1.0.2

### CODE REVIEW

**Comment by paulbalandan** [comment]
> * @Package I don't know if we need it it should be first namespace level under CodeIgniter
> * @Licence - We can link the license in every file
> * @author - Can be added from the git commit logs

These are no longer needed since we are using the short header format.

**Comment by najdanovicivan** [comment]
> > * @Package I don't know if we need it it should be first namespace level under CodeIgniter
> > * @Licence - We can link the license in every file
> > * @author - Can be added from the git commit logs
> 
> These are no longer needed since we are using the short header format.

Ok then. I've already disabled those so this one is ready to be merged

**Comment by najdanovicivan** [comment]
I also removed the composer.lock file and added it to .gitignore as test was failing

**Comment by louisl** [comment]
Thanks @najdanovicivan, closing this as I had to pull those changes in separately to a more recent version.

**Pull request closed without merging**
